package mr

import (
	"fmt"
	"log"
	"net"
	"net/http"
	"net/rpc"
	"os"
	"sync"
	"time"
)

type Coordinator struct {
	// Your definitions here.
	mu          sync.Mutex
	phase       Phase
	mapTasks    []TaskInfo
	reduceTasks []TaskInfo
	nReduce     int
	imFiles     [][]string // store the names of intermediate files generated by the mappers
	finalFiles  []string
}

type TaskInfo struct {
	files     []string // in case of reduce tasks, there are multiple files
	state     TaskState
	startTime time.Time
}
type Phase int

const (
	MapPhase Phase = iota
	ReducePhase
	Finish
)

type TaskState int

const (
	Scheduled TaskState = iota
	InProcess
	Done
)

// Your code here -- RPC handlers for the worker to call.

func (c *Coordinator) AllocateWork(args *RequestTaskArgs, reply *RequestTaskReply) error {

	c.mu.Lock()
	defer c.mu.Unlock()
	// allocate mapping or reducing work, depending on the phase
	// ask the worker to stop if all work are finished
	// put the worker on wait, if too much worker

	if c.phase == Finish {
		reply.TaskType = ExitTask
		return nil
	} else if c.phase == MapPhase {
		// find the first task to be scheduled
		var nextTask *TaskInfo
		var taskID int
		for i := range c.mapTasks {
			task := &c.mapTasks[i]
			if task.state == Scheduled {
				nextTask = task
				taskID = i
				break
			}
		}
		// if all works are Inprocess, tell the new worker to wait
		if nextTask == nil {
			reply.TaskType = WaitTask
		} else {
			reply.TaskType = MapTask
			reply.FileNames = nextTask.files
			reply.NReduce = c.nReduce
			reply.TaskId = taskID

			nextTask.startTime = time.Now()
			nextTask.state = InProcess
		}
	} else {
		//c.phase == ReducePhase
		// assume []reduceTask has been initialized somewhere else
		var nextTask *TaskInfo
		var taskID int
		for i := range c.reduceTasks {
			task := &c.reduceTasks[i]
			if task.state == Scheduled {
				nextTask = task
				taskID = i
				break
			}
		}
		// if all works are Inprocess, tell the new worker to wait
		if nextTask == nil {
			reply.TaskType = WaitTask
		} else {
			reply.TaskType = ReduceTask
			reply.FileNames = nextTask.files
			reply.NReduce = c.nReduce
			reply.TaskId = taskID

			nextTask.startTime = time.Now()
			nextTask.state = InProcess
		}
	}

	return nil
}

func (c *Coordinator) UpdateWork(args *UpdateArgs, reply *UpdateReply) error {

	c.mu.Lock()
	defer c.mu.Unlock()

	if c.phase == MapPhase && args.TaskType != MapTask {
		return fmt.Errorf("received reduce update during map phase")
	}

	if c.phase == ReducePhase && args.TaskType != ReduceTask {
		return fmt.Errorf("received map update during reduce phase")
	}
	id := args.TaskId
	if args.TaskType == MapTask {
		if c.mapTasks[id].state != InProcess {
			return nil
		}
		c.mapTasks[id].state = Done
		c.imFiles[id] = args.FileNames
		return nil
	} else if args.TaskType == ReduceTask {
		if c.reduceTasks[id].state != InProcess {
			return nil
		}
		c.reduceTasks[id].state = Done
		c.finalFiles[id] = args.FileNames[0]
		return nil
	} else {
		return fmt.Errorf("error when updating the works")
	}

}

// an example RPC handler.
//
// the RPC argument and reply types are defined in rpc.go.
func (c *Coordinator) Example(args *ExampleArgs, reply *ExampleReply) error {
	reply.Y = args.X + 1
	return nil
}

// start a thread that listens for RPCs from worker.go
func (c *Coordinator) server(sockname string) {
	rpc.Register(c)
	rpc.HandleHTTP()
	os.Remove(sockname)
	l, e := net.Listen("unix", sockname)
	if e != nil {
		log.Fatalf("listen error %s: %v", sockname, e)
	}
	go http.Serve(l, nil)
}

// main/mrcoordinator.go calls Done() periodically to find out
// if the entire job has finished.
func (c *Coordinator) Done() bool {
	ret := false

	// Your code here.
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.phase == Finish {
		ret = true
	}
	return ret
}

// create a Coordinator.
// main/mrcoordinator.go calls this function.
// nReduce is the number of reduce tasks to use.
func MakeCoordinator(sockname string, files []string, nReduce int) *Coordinator {
	c := Coordinator{}

	// Your code here.
	c.nReduce = nReduce
	c.phase = MapPhase

	// initialize map tasks
	for _, f := range files {
		c.mapTasks = append(c.mapTasks, TaskInfo{files: []string{f}, state: Scheduled, startTime: time.Time{}})
	}

	for i := 0; i < nReduce; i++ {
		// update this later
		c.reduceTasks = append(c.reduceTasks, TaskInfo{files: []string{}, state: Scheduled, startTime: time.Time{}})
	}

	c.imFiles = make([][]string, len(files))
	c.finalFiles = make([]string, nReduce)
	// todo: the coor should periodically check on dead workers
	// the dead workers should also restart themselves

	go func() {

		ticker := time.NewTicker(500 * time.Millisecond)
		defer ticker.Stop()

		for {
			<-ticker.C

			c.mu.Lock()

			if c.phase == Finish {
				c.mu.Unlock()
				return
			}

			c.checkTimeouts()
			c.checkCompletion()

			c.mu.Unlock()
		}
	}()
	c.server(sockname)
	return &c
}

func (c *Coordinator) checkTimeouts() {
	if c.phase == MapPhase {
		for i := range c.mapTasks {
			task := &c.mapTasks[i]
			if task.state == InProcess && time.Since(task.startTime) > 10*time.Second {
				task.state = Scheduled
			}
		}
	}
	if c.phase == ReducePhase {
		for i := range c.reduceTasks {
			task := &c.reduceTasks[i]
			if task.state == InProcess && time.Since(task.startTime) > 10*time.Second {
				task.state = Scheduled
			}
		}
	}
}

// check if the map phase has completed.
// if so, transition to the reduce phase and initialize  []reduceTaks
// also check if the reduce phase has completed, if so change the phase to finish
func (c *Coordinator) checkCompletion() {

	if c.phase == MapPhase {
		cmplt := true
		for _, task := range c.mapTasks {
			cmplt = cmplt && (task.state == Done)
		}
		if cmplt == true {
			// fill []reducetasks files from imfiles

			var bucketID, taskID int
			for _, fs := range c.imFiles {
				for _, f := range fs {
					_, err := fmt.Sscanf(f, "mr-%d-%d", &taskID, &bucketID)
					if err != nil {
						panic(err)
					}
					c.reduceTasks[bucketID].files = append(c.reduceTasks[bucketID].files, f)
				}
			}
			c.phase = ReducePhase
		}
		return
	}
	if c.phase == ReducePhase {
		cmplt := true
		for _, task := range c.reduceTasks {
			cmplt = cmplt && (task.state == Done)
		}
		if cmplt == true {
			c.phase = Finish
		}
		return
	}
}
